embedding_size: 64
n_ui_layers: 3
n_layers: 1
uu_layers : 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-04
knn_k: 15
learning_rate: 0.001
cl_temper: 0.2
cl_loss: 0.01

cl_temp: 0.5
cl_coef: 0.0
eps: 0.1
hyper_parameters: []
